meta:
  name: 'DKCoinsCoinBooster English'
  module: 'DKCoinsCoinBooster'
  language:
    name: 'English'
    localizedName: 'English'
    code: 'en'
messages:
  dkcoins.booster.prefix: '&8» &6Booster &8|&f'
  dkcoins.booster.personal: '${dkcoins.booster.prefix} &a+ &8{amount}$ '
  dkcoins.booster.server: '${dkcoins.booster.prefix} &a+ &8{amount}$ &7by &e{booster.displayName}'

  dkcoins.booster.command.help: '${dkcoins.booster.prefix} &7Booster help'
  dkcoins.booster.command.not.found: '${dkcoins.booster.prefix} &cThe booster &e{name} &7was not found'
  dkcoins.booster.command.not.enough: '${dkcoins.booster.prefix} &cYou don''t have enough booster'
  dkcoins.booster.command.playerNotFound: '${dkcoins.booster.prefix} &cThe player &e{player} &cwas not found'
  dkcoins.booster.command.list: '${dkcoins.booster.prefix} &7Boosters&8: @for("booster" in {boosters},${dkcoins.booster.command.list.loop},"\n","\n")'
  dkcoins.booster.command.list.loop: ' &8- &e{booster.boost.name}&8: &7{booster.amount}'
  dkcoins.booster.command.added: '${dkcoins.booster.prefix} &e{amount} &e{booster} &7booster was added to &e{player.displayName}'
  dkcoins.booster.command.removed: '${dkcoins.booster.prefix} &e{amount} &e{booster} &7booster was removed from &e{player.displayName}'
  dkcoins.booster.command.cleared: '${dkcoins.booster.prefix} &cThe boosters &e{name} &7of &e{player.displayName} &7were cleared'
  dkcoins.booster.command.disabled: '${dkcoins.booster.prefix} &cAll active boosters 7were disabled'
  dkcoins.booster.command.activated.personal: '${dkcoins.booster.prefix} &7The booster &e{booster} &8(&a{percentage}%&8) was activated'
  dkcoins.booster.command.activated.server: '${dkcoins.booster.prefix} &7The booster &e{booster} &8(&a{percentage}%&8) &7was activated by {booster.displayName}'
